### ISSUE TITLE
Empty BOM upload for dotnet projects 

### ISSUE THREAD

**Issue by liamhogan3** [CycloneDX/cyclonedx-dotnet#651] opened 2023-01-27 12:40 UTC
I have been experiencing an issue which seems to only pertain to the cyclonedx dotnet tool. Using the API to upload a set of BOMs for a given project, only the shell of the project is populated, resulting in no data being stored. This happens after a set of successful 200s from the upload call itself. I have attached a screenshot. The top two "empty" projects are dotnet, whereas the bottom two are Node and Python, which work as expected. 

![image](https://user-images.githubusercontent.com/101427755/215089277-fccdfbb9-e933-46ff-ad70-9835f82db27b.png)

**Comment by Bertk** [comment] 2023-05-12 04:25
Please check the generated bom file of cyclonedx dotnet tool. This might be empty because some configuration is missing.

**Comment by CodeTigerCloud** [comment] 2023-09-10 15:43
Since the issue is from January, and we didn't hear anything more, I am going to close this.

Feel free to open a new issue (preferable with more information), if the problem persists.

**Comment by CodeTigerCloud** [comment] 2023-09-10 15:44
Since the issue is from January, and we didn't hear anything more, I am going to close this.

Feel free to open a new issue (preferable with more information), if the problem persists.

**Closed by CodeTigerCloud** 2023-09-10 15:44 UTC
