### ISSUE TITLE
EMPTY BOM File is getting created 

### ISSUE THREAD

**Issue by gauti11** [CycloneDX/cyclonedx-dotnet#490] opened 2022-02-10 23:29 UTC
So I am working on azure pipeline and was planning to use the cyclonedx for dependency track for our dotnet project

I am using the latest version of cyclone dx:

```
Tool 'cyclonedx' is already installed.
Tool 'cyclonedx' was reinstalled with the latest stable version (version '2.3.0').
```

Able to create a BOM file but without the appropriate reference contents.

So for my creation of BOM , its not able to find the project.assets.json.(I have multiple csproj files which are being referred from the .sln file)
But this file actually exists in the different folder , when I checked my Nuget restore Task: 

`Writing assets file to disk. Path: D:\BuildAgent\_work\54\b\obj\BestPractices.Services\project.assets.json`

And while the creation of BOM tasks, it actually throws this error.

```
» Analyzing: D:\BuildAgent\_work\54\s\src\BestPractices.Peer\BestPractices.Peer.csproj
  Attempting to restore packages
  Packages restored
File not found: "D:\BuildAgent\_work\54\s\src\BestPractices.Peer\obj\project.assets.json", "D:\BuildAgent\_work\54\s\src\BestPractices.Peer\BestPractices.Peer.csproj" 
  No packages found


» Analyzing: D:\BuildAgent\_work\54\s\src\BestPractices.Services\BestPractices.Services.csproj
  Attempting to restore packages
  Packages restored
File not found: "D:\BuildAgent\_work\54\s\src\BestPractices.Services\obj\project.assets.json", "D:\BuildAgent\_work\54\s\src\BestPractices.Services\BestPractices.Services.csproj" 
  No packages found
```

I did a dotnet clean and dotnet restore but its always trying to search the Build.SourcesDirectory while the json files are in Build.BinariesDirectory. Is there any way we can look into specific folder maybe through cyclonedx

**Comment by Bertk** [comment] 2023-05-12 06:40
Please use latest version **2.7.0** and the **-biop** parameter.

`-biop|--base-intermediate-output-path <BASE_INTERMEDIATE_OUTPUT_PATH>`  **Optionally provide a folder for customized build environment. Required if folder 'obj' is relocated.**

**Comment by CodeTigerCloud** [comment] 2023-09-10 15:57
Since the issue is from February last year, and we didn't hear anything more, I am going to close this.

Feel free to open a new issue, if you still have the problem.

**Closed by CodeTigerCloud** 2023-09-10 15:57 UTC
