### ISSUE TITLE
Cannot install the nuget 

### ISSUE THREAD

**Issue by rubaroca** [CycloneDX/cyclonedx-dotnet#738] opened 2023-07-20 11:34 UTC
I am getting this error, installing from nuget:

Error	NU1202	Package CycloneDX 2.8.1 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package CycloneDX 2.8.1 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net7.0 (.NETCoreApp,Version=v7.0) / any		

Any suggestion? 
Thanks

**Comment by rubaroca** [comment] 2023-08-08 08:46
I am using this version

![image](https://github.com/CycloneDX/cyclonedx-dotnet/assets/62359950/e9a62abb-85a7-48a0-a57a-c70c358195fa)

**Comment by Bertk** [comment] 2023-08-15 14:41
Hi,
this is a `dotnet tool` and will be installed with CLI (see [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools)).

<img width="343" alt="image" src="https://github.com/CycloneDX/cyclonedx-dotnet/assets/2315215/41a96606-c895-4cca-9fea-f9d658b7c185">

The tool can be used within a build pipeline (see [example CLI](https://github.com/CycloneDX/cyclonedx-dotnet/blob/47967d7e7eccb21e0b6779fb076376a5db5b7b9c/.github/workflows/release.yml#L56C1-L59C126)) or you use the [GitHub action](https://github.com/CycloneDX/gh-dotnet-generate-sbom) (see [example GitHub action](https://github.com/CycloneDX/cyclonedx-dotnet/blob/47967d7e7eccb21e0b6779fb076376a5db5b7b9c/.github/workflows/release.yml#L61C1-L65C59))

**Comment by CodeTigerCloud** [comment] 2023-09-10 15:31
I assume Bertk answer solved the problem.

If you need further assistance, feel free to open a new issue.

**Comment by CodeTigerCloud** [comment] 2023-09-10 15:45
Since the issue is from January, and we didn't hear anything more, I am going to close this.

Feel free to open a new issue (preferable with more information), if the problem persists.

**Closed by CodeTigerCloud** 2023-09-10 15:45 UTC
