### ISSUE TITLE
Respect redirection of output folders

### ISSUE THREAD

**Issue by IoBes** [CycloneDX/cyclonedx-dotnet#608] opened 2022-10-31 10:22 UTC
Use Directory.Build.props to redirect intermediate output path's for projects,

tool  tries to look for "project.assets.json" files, but do nor respect redirection, so nothing will be found.

---------------------------------------- Directory.Build.props example ----------------------------------

<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	
	<PropertyGroup>
		<BuildRoot>$(MSBuildThisFileDirectory)</BuildRoot>
		<BuildRoot>$([System.IO.Path]::GetFullPath( $(BuildRoot) ))</BuildRoot>
		<VersionBuildLabel>$([System.DateTime]::Now.Subtract($([System.DateTime]::Today)).TotalMinutes.ToString('00000'))</VersionBuildLabel>
		<VersionBuildTime>$([System.DateTime]::Now.ToString('ddMMyyyyHHmmss'))</VersionBuildTime>
	</PropertyGroup>

	<PropertyGroup>
		<Platforms>AnyCPU</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<ForceGenerationOfBindingRedirects>true</ForceGenerationOfBindingRedirects>
		<TargetFramework>net6.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<LangVersion>10.0</LangVersion>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<NoWarn>$(NoWarn);NU1603;NU5105;NU5125;1701;1702</NoWarn>
		<PublishRepositoryUrl>false</PublishRepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'==''">
		<BaseIntermediateOutputPath>$(BuildRoot)build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
		<BaseOutputPath>$(BuildRoot)build\platform\</BaseOutputPath>
	</PropertyGroup>

	
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)'=='Debug|net6.0'">
		<BaseIntermediateOutputPath>$(BuildRoot)build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
		<BaseOutputPath>$(BuildRoot)build\platform\</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)'=='Release|net6.0'">
		<BaseIntermediateOutputPath>$(BuildRoot)build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
		<BaseOutputPath>$(BuildRoot)build\release\platform\</BaseOutputPath>
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)'=='Debug|net6.0-windows'">
		<BaseIntermediateOutputPath>$(BuildRoot)build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
		<BaseOutputPath>$(BuildRoot)build\platform\</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)'=='Release|net6.0-windows'">
		<BaseIntermediateOutputPath>$(BuildRoot)build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
		<BaseOutputPath>$(BuildRoot)build\release\platform\</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<DefineConstants>$(DefineConstants);TRACE</DefineConstants>
	</PropertyGroup>
</Project>

**Comment by Bertk** [comment] 2023-05-07 09:23
Please use **-biop** parameter with the real path (environment variables are not supported).  

![image](https://user-images.githubusercontent.com/2315215/236668878-3a9a2a62-2d1a-4810-a90d-4f8f295ac521.png)

**Comment by CodeTigerCloud** [comment] 2023-09-10 15:51
Since the issue is from October last year, and we didn't hear anything more and Bertk solution looks helpful, I am going to close this. 

Feel free to open a new issue (preferable with more information), if the problem persists.

**Closed by CodeTigerCloud** 2023-09-10 15:51 UTC
