### ISSUE TITLE
Unable to find bom ref for solutions which depend both on the project and the package of a library

### ISSUE THREAD

**Issue by lgrguricmileusnic** [CycloneDX/cyclonedx-dotnet#758] opened 2023-09-13 12:49 UTC
### **CycloneDX version: 2.8.1**

**Expected:**
> During dependency enumeration, if a dependency on a project and a package with the same name exists, the SBOM should be generated normally.

**Actual**
> During dependency enumeration, an error occurs:
`Unable to locate valid bom ref for SomeProject [1.2.3, )`

ProjectAssetsFileService excludes all project target runtime libraries in the GetSolutionNugetPackages method which is probably intended (https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/CycloneDX/Services/ProjectAssetsFileService.cs#L43).

However this causes the error in Program.cs when a package depends on another package which is also referenced to as a project somewhere else in the solution:
```cs
                foreach (var package in packages)
                {
                    var packageDependencies = new Dependency
                    {
                        Ref = bomRefLookup[(package.Name.ToLower(CultureInfo.InvariantCulture), package.Version.ToLower(CultureInfo.InvariantCulture))],
                        Dependencies = new List<Dependency>()
                    };
                    if (package.Dependencies != null && package.Dependencies.Any())
                    {
                        foreach (var dep in package.Dependencies)
                        {
                            var lookupKey = (dep.Key.ToLower(CultureInfo.InvariantCulture), dep.Value.ToLower(CultureInfo.InvariantCulture));
                            if (!bomRefLookup.ContainsKey(lookupKey))
                            {
                                var packageNameMatch = bomRefLookup.Where(x => x.Key.Item1 == dep.Key.ToLower(CultureInfo.InvariantCulture)).ToList();
                                if (packageNameMatch.Count == 1)
                                {
                                    lookupKey = packageNameMatch.First().Key;
                                }
                                else
                                {
                                    Console.Error.WriteLine($"Unable to locate valid bom ref for {dep.Key} {dep.Value}");
                                    return (int)ExitCode.UnableToLocateDependencyBomRef;
                                }
                            }

                            var bomRef = bomRefLookup[lookupKey];
                            transitiveDependencies.Add(bomRef);
                            packageDependencies.Dependencies.Add(new Dependency
                            {
                                Ref = bomRef
                            });
                        }
                    }
                    dependencies.Add(packageDependencies);
                }
            }
```

This happens because bomRefLookup is filled using only packages supplied by SolutionFileService through ProjectFileService and ProjectAssetsFileService (when using a .sln file).

```cs
                var bomRefLookup = new Dictionary<(string, string), string>();
                foreach (var package in packages)
                {
                    var component = await nugetService.GetComponentAsync(package).ConfigureAwait(false);
                    if (component != null)
                    {
                        if (component.Scope != Component.ComponentScope.Excluded || !excludeDev)
                        {
                            components.Add(component);
                        }
                        packageToComponent[package] = component;
                        bomRefLookup[(component.Name.ToLower(CultureInfo.InvariantCulture), (component.Version.ToLower(CultureInfo.InvariantCulture)))] = component.BomRef;
                    }
                }
```

Proposed solution would be to also add referenced projects to bomRefLookup and the final SBOM.

Edit 30.11.2023.
I created a poc with compiled nupkgs here https://github.com/lgrguricmileusnic/cyclonedx-dotnet-bug-poc/tree/master

**Comment by CodeTigerCloud** [comment] 2023-10-05 17:23
Hello @lgrguricmileusnic,
I'm a little confused about packages that have project dependencies. 
Can you give me an example for that?

**Comment by SchneiderMikeTriplett** [comment] 2023-10-17 14:50
> Hello @lgrguricmileusnic, I'm a little confused about packages that have project dependencies. Can you give me an example for that?

I believe he meant when one project in a solution references another project in the solution.

**Comment by sawtoothHman** [comment] 2023-11-07 23:29
I ran into this same situation, I'm on version 2.9, however. I have a project in a solution that references another project in the same solution and saw this same error message. 

Forgive my ignorance if that is bad practice to do in a solution file and was therefore not intended to be supported for generating an SBOM. But if that is OK to do in the .NET world, I second the solution proposed.

**Comment by CodeTigerCloud** [comment] 2023-11-08 17:09
@sawtoothHman 

> I have a project in a solution that references another project in the same solution and saw this same error message.

> Forgive my ignorance if that is bad practice to do in a solution file and was therefore not intended to be supported for generating an SBOM. But if that is OK to do in the .NET world, I second the solution proposed.

No, of course that is not bad practise and the normal case that works thousands of times every day. We need to figure out what's special about your case.

Is the referenced project in .net standard, what .net version is the referencing project? 
.NET Standard seems to be connected to the problem in #739?

**Comment by sawtoothHman** [comment] 2023-11-08 17:54
Thanks for your response! I'll try to answer your question as best as I can since C#/ .NET is not my strong suit.

I'm working with .NET 6.0 for this entire project, both the referenced and referencing projects. 

The exact error message I get is:
`Unable to locate valid bom ref for Grpc.Tools [2.58.0, ) referenced by (Name: Grpc.AspNetCore Version: 2.58.0)`

That message pops up when processing a csproj file with a project reference to another csproj file from the solution.

The referenced project certainly includes Grpc.AspNetCore Version: 2.58.0, which 
 https://www.nuget.org/packages/Grpc.AspNetCore/2.58.0#dependencies-body-tab lists Grpc.Tools version 2.58 as a dependency.

That referenced project file also explicitly included Grpc.Tools version 2.59 as well as a few other Grpc packages at the time I got the first error message. 

Seeing that Grpc has version 2.59 for all of those packages as of 12 hours ago, I tested this with version 2.59 everywhere for the Grpc packages and the only difference is that the error message now says 
`Unable to locate valid bom ref for Grpc.Tools [2.59.0, ) referenced by (Name: Grpc.AspNetCore Version: 2.59.0)`

**Comment by CodeTigerCloud** [comment] 2023-11-08 19:39
Sadly, I cannot reproduce the error, here are the steps I tried to reproduce:

New solution with console application: ConsoleApp10.csproj
Add project ClassLibrary1.csproj
Add grpc.AspNetCore via nuget to Class Library1.
Add reference to ClassLibrary from ConsoleApp.

I call: `dotnet cycloneDX -o C:\temp D:\src\ConsoleApp10\ConsoleApp10\ConsoleApp10.csproj`

It creates a valid looking bom without the error.

What parameters do you call CycloneDX with? Maybe there is a combination that causes the problem.

**Comment by sawtoothHman** [comment] 2023-11-08 20:06
I really appreciate your efforts in trying to reproduce my situation. You may have missed my edit with my guess as to the issue, that guess seems to have been it.

After I removed the redundant and different version package reference to Grpc.Tools in the referenced project, the bom was generated successfully (and automatically loaded into my Dependency Track instance for analysis, love that tool too!). I still need to make sure the rest of the tests pass, but I think things are looking shiny now.

Why oh why explicitly include another reference to an already-transitively included package and then make it a different version? No idea...but I'm not gonna sift through the git history to find out who and to ask why because I doubt they would even know.

For reference, I was using `dotnet CycloneDX solutionFile.sln -o ./outputDir/ -f service-bom.json  -j -dgl -t`. These options work great for my use case; it was just this one particular project that was not generating the bom correctly until I noticed this issue.

**Comment by CodeTigerCloud** [comment] 2023-11-08 21:48
Glad you could solve your issue and that you enjoy the tool family.

CycloneDX should still be able to resolve the duplicate reference with it, as msbuild is also able to resolve and build it. 

Thank you for reporting your solution, it might help me to fix the problem and serve others as a workaround.

**Comment by lgrguricmileusnic** [comment] 2023-11-30 15:45
> Hello @lgrguricmileusnic, I'm a little confused about packages that have project dependencies. Can you give me an example for that?

Hi @CodeTigerCloud , I wasn't able to get back to this until now. I edited my issue due to numerous errors in my initial post. I also created a PoC since I narrowed down the cause:
https://github.com/lgrguricmileusnic/cyclonedx-dotnet-bug-poc/tree/master

The error occurs if references both to the project and the package of the same library exist in a solution. I illustrated it better in the PoC README. 

The problem is in the ProjectAssetsFileService.cs code during runtime packages enumeration [line 58](https://github.com/CycloneDX/cyclonedx-dotnet/blob/2eaaeaaaa34f24bf137325f5c7d526d649965822/CycloneDX/Services/ProjectAssetsFileService.cs#L58).

Since the project.assets.json file generated by dotnet restore defines the library as a project, it is excluded as a possibly depended-on package from the runtimePackages set.

**Comment by CodeTigerCloud** [comment] 2023-12-06 17:22
I guess the goal is to replace the incoming package with your own implementation? I assume the project has priority over the package.

I understand your problem, I will see look into it and hopefully deploy a fix in the next version.

**Comment by CodeTigerCloud** [comment] 2023-12-16 21:51
This is actually connected to #785.

The "Dependency" gets listed as a project reference in the project.assets.json and currently project-files are ignored by CycloneDX.
That's why the dependency of "Dependent" cannot be resolved. 

It was not foreseen that a package can have a project reference. (it is a little bit perverted to be honest).

**Comment by mtsfoni** [comment] 2023-12-28 12:51
Fixed with the new release. 
With the new -ipr the shadowing project should be shown as component. Without -ipr the dependency should not appear in the bom at all.

https://github.com/CycloneDX/cyclonedx-dotnet/releases/tag/v3.0.0

**Closed by mtsfoni** 2023-12-28 12:51 UTC
