### ISSUE TITLE
Invalid BOM generated

### ISSUE THREAD

**Issue by stephanruhland-netzebw** [CycloneDX/cyclonedx-dotnet#757] opened 2023-09-11 11:58 UTC
Hi,
CycloneDX DotNet in Version 2.8.1.0 seems to write invalid BOM.XML files. The validation error on CycloneDX Web Tool is the following message:

`Validation failed at line number 623 and position 28: The 'http://cyclonedx.org/schema/bom/1.4:id' element is invalid - The value 'NOASSERTION' is invalid according to its datatype 'http://cyclonedx.org/schema/spdx:licenseId' - The Enumeration constraint failed.`

So the value "NOASSERTION" is not a valid enum value for the licenseid. The part of the xml can be seen here:
![image](https://github.com/CycloneDX/cyclonedx-dotnet/assets/135113967/fa4749c3-4e9a-40ac-943a-19bee4c10279)

Are there ideas for this case?
Thank you

**Comment by CodeTigerCloud** [comment] 2023-09-12 16:21
Thank you for reporting.

Duplicate of #525.
See my latest reply there for more information.

**Closed by CodeTigerCloud** 2023-09-12 16:21 UTC

**Comment by stephanruhland-netzebw** [comment] 2023-09-14 08:09
Thank you for the quick reply
